# Generated by Django 4.0.6 on 2022-08-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='category',
            field=models.CharField(choices=[('L', 'Leisure'), ('W', 'Work')], default='L', max_length=1),
        ),
    ]
